### ISSUE TITLE
[fix] 3차 스프린트 QA 수정사항 반영 

### ISSUE THREAD

**Issue by Doreminwoo** [TeamPINGLE/PINGLE-ANDROID#242]
## What is this issue? 🛠
3차 스프린트 QA 수정사항 반영 
## Progress 🏃‍♀️
- [x] 스플래시 - 로그인 이후 앱 재실행시 (온보딩X) 입장방식선택으로 가야됌
- [x] 온보딩(기존단체입장) - 단체 키워드 정렬 안되어있음(왼쪽에 붙어있어요)
- [ ] 온보딩(기존단체입장) - 직접 입력할 때 → 흰색, 복사할 때 → 검정색
- [x] 온보딩(신규단체개설) - 안내페이지 갔다 돌아오면 중복확인 스낵바 나옴..
- [ ] 온보딩(신규단체개설) - 안내페이지, 뒤로가기 시 chip 선택해제 등 데이터 저장..
- [x] 전체적으로 단체명 2줄 확인
- [x] 데이터 텍소노미 스크롤 시점으로 변경

**Comment by jihyunniiii** [comment]
데이터 텍소노미 스크롤 시점으로 변경 -> 이것도 있숨!!
그리고 return 버튼은 저한테도 동일하게 있어서 제가 먼저 해보겠슴다 다른 거 먼저 하세용 ~

**Comment by jihyunniiii** [comment]
민우오빠 키보드 return 버튼 제가 했어요 ~ 서치바 들어가는 부분에 모두 적용해야 한다구 해서 커스텀 서치바에서 일괄로 적용했습니다 !
